import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ 
  subsets: ['latin'],
  display: 'swap',
  weight: '500'
 })

export const metadata: Metadata = {
  title: '3engine homepage',
  description: '3engine homepage, generated by NextJS/TypeScirpt/TailwindCSS',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
